language: node_js
node_js:
- stable
services:
  - mongodb
cache:
  directories:
  - node_modules
git:
  depth: 3
script:
  - travis_wait npm run test:coverage
after_script:
  - travis_wait npm run report-coverage
